[package]
name = "einstellung"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
description = "A Rust Configuration Parser"
license = "MIT OR Apache-2.0"
repository = "https://github.com/soruh/einstellung"

[package.metadata.docs.rs]
all-features = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
serde_path_to_error = { version = "0.1.20", optional = true }

serde_json = { version = "1.0", optional = true }
dotenvy = { version = "0.15.7", optional = true }
serde_saphyr = { package = "serde-saphyr", version = "1.2.0", default-features = false, features = ["deserialize"], optional = true }
toml = { version = "0.9.8", optional = true }

einstellung_derive = { version = "0.2.0", path = "../einstellung_derive", optional = true }

[[example]]
name = "simple"
required-features = ["derive", "json", "toml", "yaml"]

[[example]]
name = "layered"
required-features = ["derive", "json", "toml", "yaml"]

[dev-dependencies]
anyhow = "1.0"
insta = "1.46.3"


[features]
derive = ["dep:einstellung_derive"]

dotenv = ["env", "dep:dotenvy"]
env = ["key-value"]
key-value = ["dep:serde_json"]
json = ["dep:serde_json", "dep:serde_path_to_error"]
toml = ["dep:toml", "dep:serde_path_to_error"]
yaml = ["dep:serde_saphyr", "dep:serde_path_to_error"]

full = ["dotenv", "env", "json", "toml", "yaml", "derive"]

default = ["json", "toml", "yaml", "derive"]

[lints]
workspace = true
