name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install rust-src
        run: rustup component add rust-src

      - name: Cache cargo registry + build
        uses: Swatinem/rust-cache@v2

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run integration tests
        env:
          CARGO_TERM_COLOR: always
        working-directory: einstellung/
        run: cargo nextest run

      - name: Run derive tests
        env:
          CARGO_TERM_COLOR: always
        working-directory: einstellung_derive/
        run: cargo nextest run
